### ISSUE TITLE
Configuration not being published?

### ISSUE THREAD

**Issue by matthijs110** [AltThree/Locker#10]
After I pulled in the package (`composer require alt-three/locker`) and registered the LockerServiceProvider (`AltThree\Locker\LockerServiceProvider::class,`), the publish command has  no `locker.php` config file to publish. I tried to reinstall it, but that didn't work. 

Also: I want to use the middleware. Can I just do it like `->middleware('locker');`?

**Comment by GrahamCampbell** [comment]
> Also: I want to use the middleware. Can I just do it like ->middleware('locker');?

No, you'll need the full middleware name. Just import `AltThree\Locker\Http\Middleware\LockingMiddleware`, and then use `LockingMiddleware::class` as the name.

**Comment by GrahamCampbell** [comment]
> has no locker.php config file to publish. I tried to reinstall it, but that didn't work.

Looks like you forgot to clear your cached config. Recache it using `php artisan config:cache`.

**Comment by matthijs110** [comment]
That did the job :)

One question though; can I do the following:

If people spam a post button, the request is being executed multiple times. With Laravel for example: a notification is sent multiple times (the x amount of times the button has clicked).

**Comment by GrahamCampbell** [comment]
Those sorts of question span beyond bug reports with this package I'm afraid. Please feel free to discuss implementation of that on the laravel forums or something. :)

One thing you can do is use our throttle package: https://github.com/AltThree/Throttle. In newer version of laravel, floating point values are supported for cache time, so you can set decay to less the 1 min, say, 6 seconds, (0.1). That would do the job stopping spam posts. Maybe 30 seconds is what you want (0.5).

**Comment by matthijs110** [comment]
Thank you for your help. I'll definitely take a look in to Throttle.
