### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by kylestev** [AltThree/Locker#11]
Currently this package does not support 5.4 and blocks installation. Any idea on a timeline for 5.4 support?

**Comment by GrahamCampbell** [comment]
Yes, 2.x supports Laravel 5.4. :)

**Comment by GrahamCampbell** [comment]
You can see the changes here: https://github.com/AltThree/Locker/compare/1.6...master.

**Comment by kylestev** [comment]
Whoops. Totally missed the major version release! My apologies 😅
