### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by COLABORATI** [AltThree/Locker#12]
you seem to oversee how important docs are... in this project also no docs?

**Comment by matthewlilley** [comment]
Are you having trouble with something?

**Comment by zietbukuel** [comment]
Do we have to read the whole source code and figure out how to use this package?

**Comment by GrahamCampbell** [comment]
We'd accept contributions to add documentation. Fortunately, this package is very small, so doesn't take long to read. The main point of interface is https://github.com/AltThree/Locker/blob/master/src/Locker.php. You can call the execute method with a function. You can see the middleware for an example: https://github.com/AltThree/Locker/blob/master/src/Http/Middleware/LockingMiddleware.php#L78.
