### ISSUE TITLE
Remove Predis as a composer requirement

### ISSUE THREAD

**Issue by rodrigopedra** [AltThree/Locker#13]
Hi,

Is it feasible to remove predis as a composer requirement? I use the php-redis extension on my project and having predis installed conflicts with it.

I can send a PR if you don't see a problem removing it.

Thanks!

**Comment by GrahamCampbell** [comment]
We have the problem that the package is required if the extension is not installed, and the package is always required on older version of laravel.

> having predis installed conflicts with it.

Does it? I've never tried. How does it conflict please? It'd be really useful to get more information. :)

**Comment by GrahamCampbell** [comment]
If you need an immediate work around for this, what you can do in your app's `composer.json` file is do this:

```json
    "replace": {
        "predis/predis": "*"
    },
```

Hope that helps! Bit of a hack, but will fix your issue. :)

---

Extra background:

For example, in one of my apps, I have:

```
    "require": {
        "php": "^7.1",
        ...
    }
```

So to avoid having polyfill packages installed, I have the following:

```json
    "replace": {
        "paragonie/random_compat": "*",
        "symfony/polyfill-php56": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php71": "*"
    }
```

**Comment by rodrigopedra** [comment]
I worked on a project where it throwed an exception if we had predis and phpredis extension both installed. It was fixed by removing predis as a requirement.

But I just tested locally in some other projects I am working now and this does not happen. I am not sure what happened then...

Sorry for any inconvenience, and thanks for the tips to resolve requirements conflicts.
