### ISSUE TITLE
What should the correct HTTP exception code be?

### ISSUE THREAD

**Issue by GrahamCampbell** [AltThree/Locker#19]
Hello everyone. Currently, when we are unable to acquire the lock, we throw an `UnprocessableEntityHttpException` (status code 422). I am wondering if this is really the best choice. Would 423 be better? It seems odd to use either 422 or 423, since they are designed for WebDAV. I can't think which of the codes would be best.

Maybe we should just go for 429: too many requests?

**Comment by dlucian** [comment]
I'd go with 423 (Locked) if that can be gracefully handled by the client app, as the client might want to retry the exact same operation after a while (few seconds for example). 

422 Unprocessable Entity means the client is sending incomplete or invalid information, and should not be repeated with the exact same information.

**Comment by GrahamCampbell** [comment]
The thing with 423 is it's meant to only be used by webdav. It implies the current resource is locked. The thing is, the resource is not locked, we're just wanting to limit the concurrent requests, which is why I think maybe sating 429 is better. Like, we're saying, the client is going too fast.

So yeh, d'no. It's between 423 and 429 I guess.

**Comment by GrahamCampbell** [comment]
Alright. As of `v5.0.0`, we're now using HTTP 423 Locked. ;)
