### ISSUE TITLE
do it can ignore duplicate submit post ?

### ISSUE THREAD

**Issue by vahidalvandi** [AltThree/Locker#21]
user can click multiply submit form then store method run multiply . do Locker can ban duplicate request ?

**Comment by vahidalvandi** [comment]
please show how i can use locker with middlware

**Comment by GrahamCampbell** [comment]
Just add https://github.com/AltThree/Locker/blob/master/src/Http/Middleware/LockingMiddleware.php to your middleware stack in the usual way.

**Comment by GrahamCampbell** [comment]
By default, it locks all non-GET/HEAD requests per session.

**Comment by vahidalvandi** [comment]
thank you . please create step by step use this package prevent duplicate post is very common problem

**Comment by vahidalvandi** [comment]
i installed it , but not work in non redis ?? cache driver should  to redis ?

**Comment by GrahamCampbell** [comment]
Yes, from Laravel 5.8 upwards, this doesn't need redis.

**Comment by GrahamCampbell** [comment]
It just uses Laravel's in-built locking system from 5.8 upwards.

**Comment by vahidalvandi** [comment]
i use laravel 6 but after call api return error about REDIS
