### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by kylestev** [AltThree/Locker#7]
I understand the readme states this is for Laravel 5, but the service provider has a conditional for Lumen applications. This might just be an artifact from a boilerplate service provider you use for new packages but I thought I should point out that it will not work with Lumen applications.

The first issue Lumen runs into is on [line 63](https://github.com/AltThree/Locker/blob/master/src/LockerServiceProvider.php#L73) where it attempts to call `registerLocker` with the application parameter being an instance of `Laravel\Lumen\Application` instead of the expected `Illuminate\Contracts\Foundation\Application`. Lumen also runs the same type-hinting problem with `setupConfig` after the previous issue is resolved.

While Laravel's application class ([`Illuminate\Foundation\Application`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Application.php)) does implement `Illuminate\Contracts\Foundation\Application` (what this package type-hints), Lumen's application class ([`Laravel\Lumen\Application`](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php)) does not. They do, however, both extend `Illuminate\Container\Container` - though I don't think type-hinting that would be correct given the methods being called on it are not from that class.

If you plan to support Lumen in the future, you might want to make a separate service provider just for Lumen. Additionally, if Lumen becomes supported, it might be worth mentioning in the readme that `illuminate/redis` is a required dependency (Lumen does not include this out of the box) and that you need to have the database config loaded (`$app->make('db')` will do this, though that's overkill if you don't need Eloquent) prior to `Illuminate\Redis\RedisServiceProvider` being ran.

**Comment by GrahamCampbell** [comment]
Having redis missing is NOT an issue. You MUST install that yourself if you want it.

In terms of the application typehints, I'm going to fix them on ~40 packages including this one at the weekend.

**Comment by kylestev** [comment]
Good point on `illuminate/redis`. I didn't see that it was just a Predis client instance that was required.
