### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by bathan** [AltThree/Locker#9]
Hello there. Where can I find some documentation on how to implement this Locker?

**Comment by GrahamCampbell** [comment]
Sorry, there's basically no documentation.

**Comment by GrahamCampbell** [comment]
I'd recommend just flicking through the source code, since all our phpdoc tells you how to use it. It's pretty small.

The low down is you can use the [`Locker`](https://github.com/AltThree/Locker/blob/master/src/Locker.php) class (through the [`Lock`] facade if you want), in order to execute a closure within a lock.

The function definition is:

```php
    /**
     * Acquire the a lock for, and then execute the function.
     *
     * If we were unable to acquire the lock, after the specified number of
     * attempts, then we'll throw an exception.
     *
     * @param \Closure $function
     * @param string   $name
     * @param int      $timeout
     * @param int      $play
     * @param int      $interval
     * @param int      $attempts
     *
     * @throws \AltThree\Locker\Exceptions\UnableToAcquireLockException
     *
     * @return mixed
     */
    public function execute(Closure $function, $name, $timeout, $play = 500, $interval = 100, $attempts = 128)
```

An example:

```php
<?php namespcae Foo;

use AltThree\Locker\Facades\Locker;

// this is a "thunk" that get's executed after acquiring the lock on the name "foo"
$fn = function () {
    echo "bar";
};

Locker::execute($fn, 'foo');

**Comment by GrahamCampbell** [comment]
We also have an http middleware you can use if you want to prevent concurrent "non-safe" requests from the same user: https://github.com/AltThree/Locker/blob/master/src/Http/Middleware/LockingMiddleware.php.

In particular, reading lines 69-79 (https://github.com/AltThree/Locker/blob/master/src/Http/Middleware/LockingMiddleware.php#L69-L79) will also serve as another usage example.

---

Another use case we actually have for this is locking the execution of commands on the laravel command bus. We have a command bus middleware that looks like this:

![image](https://cloud.githubusercontent.com/assets/2829600/21027679/dc667040-bd89-11e6-8f9d-83f67e62954e.png)


Where the "name" function is some disaster of a piece of code that returns a uniqueish hash of the command name with the id of the first parameter passed to it (ish):

![image](https://cloud.githubusercontent.com/assets/2829600/21027712/05029d08-bd8a-11e6-8000-de3baf76f98d.png)

This allows us to limit the number of delete account commands per user to one at a time for example, so the same user cannot delete their account twice at once, but two different users may.

**Comment by bathan** [comment]
Thank you very much!!!!
